language: julia

os:
  - linux
  - osx
  - windows
  
julia:
  - 0.7
  - 1.0
  - 1.2
  - 1.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

notifications:
    email: false
